# Generated by Django 6.1 on 2026-09-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nwgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NWChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwgroups.nwgroup')),
            ],
        ),
    ]
