# Generated by Django 6.1 on 2026-09-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwchannels', '0001_initial'),
        ('nwgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwchannel',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='nwgroups.nwgroup'),
        ),
    ]
