# Generated by Django 6.1 on 2026-09-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwchannels', '0002_alter_nwchannel_owning_group'),
        ('nwgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nwchannel',
            constraint=models.UniqueConstraint(fields=('name', 'owning_group'), name='nw_channel_'),
        ),
    ]
