# Generated by Django 6.1 on 2026-09-02 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nwchannels', '0001_initial'),
        ('nwgroups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NWMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwgroups.nwgroup')),
            ],
        ),
        migrations.CreateModel(
            name='NWUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_joined', models.ManyToManyField(related_name='nwgroups', through='nwusers.NWMembership', to='nwgroups.nwgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nwmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwusers.nwuser'),
        ),
        migrations.CreateModel(
            name='NWSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwchannels.nwchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwusers.nwuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='unique_user_subscription')],
            },
        ),
        migrations.AddConstraint(
            model_name='nwmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_membership'),
        ),
    ]
