# Generated by Django 6.1 on 2026-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwgroups', '0001_initial'),
        ('nwusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nwuser',
            old_name='user',
            new_name='auth_user',
        ),
        migrations.AlterField(
            model_name='nwuser',
            name='groups_joined',
            field=models.ManyToManyField(related_name='user_membership', through='nwusers.NWMembership', to='nwgroups.nwgroup'),
        ),
    ]
